#let title = "Seminar paper on SoC-FPGAs"
#let program = "Computer Engineering"
#let supervisor = "Prof. Dr. Michael Strohmeier"
#let author = "Benjamin Klarić"
#let university = "Technical University of Applied Sciences Augsburg"
#let description = "Seminar: New Technologies"
#let logo_path = "/figures/0_titlepage/tha.jpg"
#let bib_path = "/references.bib"
#let submissionDate = datetime(day: 14, month: 1, year: 2025)